pool:
  vmImage: windows-latest
steps:
- task: NuGetCommand@2  
  displayName: 'Restore nuget packages' 
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArguments: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="$(System.DefaultWorkingDirectory)\WebAppContent"'
- task: ArchiveFiles@2
  displayName: 'Archive $(System.DefaultWorkingDirectory)\WebAppContent'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\WebAppContent'
    includeRootFolder: false
- task: DotNetCoreCLI@2
  displayName: 'Initialize EntityFrameworkCore'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global dotnet-ef'
# - task: DotNetCoreCLI@2
#   displayName: 'Create migration'
#   inputs:
#     command: 'custom'
#     projects: '**/*.csproj'
#     custom: 'ef'
#     arguments: 'migrations script -i -o migration.sql'
- task: pekspro.pekspro-efcore-migration-script-generator.efcore-migration-script-generator.efcore-migration-script-generator-task@0
  displayName: 'Generate Migration Scripts'
  inputs:
    projectpath: DIYTracker/DIYTracker.csproj
    databasecontexts: MyDatabaseContext
    build: false
    installdependencies: true
- task: SqlAzureDacpacDeployment@1
  displayName: Install the database
  inputs:
    azureSubscription: 'Azure for Students (46fee1dd-ee7b-4bd2-b078-a79b6a52abcd)'
    AuthenticationType: connectionString
    ConnectionString: 'Server=tcp:sqlserverim64jhe4nddwu.database.windows.net,1433;Initial Catalog=DIYTracker;Persist Security Info=False;User ID=jonmillervt;Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    DacpacFile: 'migration.sql'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(Parameters.ArtifactName)'